### ISSUE TITLE
Id tags not linking to the href

### ISSUE THREAD

**Issue by christianne-mcpartland** [christianne-mcpartland/portfolio-coming-soon#15]
![screen shot 2015-10-14 at 8 21 07 pm](https://cloud.githubusercontent.com/assets/6370643/10501576/31acfaee-72b1-11e5-89eb-e32bcea38e66.png)

This is my navigation html

and this is how I've been trying to link the navigation to the different sections of my website.
The link between them is broken and when one of the nav li's is clicked on, it takes you to a 404 error page. If you could help me figure out where I have gone wrong in my code it would help me out a lot. 
@thomasjbradley
This is the rest of my code:

![screen shot 2015-10-14 at 8 23 31 pm](https://cloud.githubusercontent.com/assets/6370643/10501634/8cb60fde-72b1-11e5-9d21-e965faef2045.png)

**Comment by thomasjbradley** [comment]
There seems to be proper curly quotes around the `href` instead of code-style straight quotes.
